version: '3'

services:
  web: 
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    volumes:
      - ./src/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - internal

  php-fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    volumes:
      - ./src/:/var/www/html/
    networks:
      - internal

  postgres:
    image: postgres:14
    restart: always
    environment:
      - "TZ=Asia/Jakarta"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - internal

  cache: 
    image: redis:6.2.7
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres-data:
  cache: